databases:
  - name: microverse
    databaseName: microverse_3gfa
    user: microverse_3gfa_user

services:
  - type: web
    name: budgetApp
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name:  microverse_3gfa
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false